project:
  type: website

website:
  title: "Yogesh Dhingra"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Projects

format:
  html:
    theme: cosmo
    css: style.css
    toc: true